In [2]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score, recall_score, zero_one_loss, confusion_matrix
import sklearn.neural_network as nn
import numpy as np
import matplotlib.pyplot as plt
import time

In [3]:
mnist = fetch_openml('mnist_784')

In [4]:
#tableau de 5000 valeurs aléatoires entre à et 70000
index = np.random.randint(70000, size=5000)
#échantillon de 5000 données de Mnist
data = mnist.data[index]
#étiquettes correspondant aux 5000 données échantillons
target = mnist.target[index]
#division de la base en données d'apprentissage (70%) et de test (30%)
datatrain, datatest, targettrain, targettest = train_test_split(data, target,train_size=0.70)
#data = mnist.data
#target = mnist.target
#division de la base en données d'apprentissage (49000) et de test
#datatrain, datatest, targettrain, targettest = train_test_split(data, target,train_size=0.70)
print(datatrain.shape)

(3500, 784)


C:\Users\linam\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [5]:
mlp = nn.MLPClassifier(hidden_layer_sizes=(50))
mlp.fit(datatrain,targettrain)
mlp.score(datatest,targettest)

0.8533333333333334

In [6]:
print(targettest[3])
print(mlp.predict(datatest)[3])

2
2


In [8]:
%timeit precision_score(targettest,mlp.predict(datatest),average='micro')

131 ms ± 3.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
precisions_couches = []
temps_couches = []
tt_couches = []
rappel_couches = []
erreur_couches = []
train_precisions_couches = []
for nb_c in [2,10,20,50,70,100]:
    hls = tuple(50 for i in range(nb_c))
    mlp = nn.MLPClassifier(hidden_layer_sizes=hls)
    st = time.time()
    start_time = time.process_time()
    mlp.fit(datatrain,targettrain)
    elapsed = time.process_time()-start_time
    duration = time.time()-st
    prec = mlp.score(datatest,targettest)
    testpred = mlp.predict(datatest)
    precisions_couches.append(prec)
    temps_couches.append(elapsed)
    tt_couches.append(duration)
    rap = recall_score(targettest,testpred,average='micro')
    err = zero_one_loss(targettest,testpred)
    rappel_couches.append(rap)
    erreur_couches.append(err)
    prec_train = mlp.score(datatrain,targettrain)
    train_precisions_couches.append(prec_train)
    print("precision =", prec, "temps =", elapsed,"time =",duration,"sur train =",prec_train, "pour", nb_c,"couches")

precision = 0.84 temps = 6.59375 time = 4.224783182144165 sur train = 1.0 pour 2 couches
precision = 0.926 temps = 16.984375 time = 9.87440013885498 sur train = 1.0 pour 10 couches
precision = 0.9286666666666666 temps = 26.84375 time = 16.515713691711426 sur train = 0.9977142857142857 pour 20 couches
precision = 0.6653333333333333 temps = 36.65625 time = 19.896430015563965 sur train = 0.7065714285714285 pour 50 couches
precision = 0.11533333333333333 temps = 34.578125 time = 17.994463205337524 sur train = 0.11257142857142857 pour 70 couches
precision = 0.12 temps = 53.265625 time = 27.43538498878479 sur train = 0.11 pour 100 couches


In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('number of layers')
ax1.set_ylabel('precision', color=color)
ax1.plot([2,10,20,50,70,100],precisions_couches,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('execution time', color=color)
ax2.plot([2,10,20,50,70,100],temps_couches,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('number of layers')
ax1.set_ylabel('precision', color=color)
ax1.plot([2,10,20,50,70,100],precisions_couches,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('execution time', color=color)
ax2.plot([2,10,20,50,70,100],tt_couches,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('number of layers')
ax1.set_ylabel('precision', color=color)
ax1.plot([2,10,20,50,70,100],precisions_couches,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('rappel', color=color)
ax2.plot([2,10,20,50,70,100],rappel_couches,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('number of layers')
ax1.set_ylabel('precision test', color=color)
ax1.plot([2,10,20,50,70,100],precisions_couches,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('precision train', color=color)
ax2.plot([2,10,20,50,70,100],train_precisions_couches,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
plt.plot([2,10,20,50,70,100],erreur_couches,'+-')
plt.ylabel('error')
plt.xlabel('number of layers')
plt.show()

In [ ]:
plt.plot([2,10,20,50,70,100],temps_couches,'+-')
plt.ylabel('training time')
plt.xlabel('number of layers')
plt.show()

In [ ]:
plt.plot([2,10,20,50,70,100],tt_couches,'+-')
plt.ylabel('training time')
plt.xlabel('number of layers')
plt.show()

In [11]:
precisions_neurones = []
temps_neurones = []
tt_neurones = []
rappel_neurones = []
erreur_neurones = []
for nb_n in [5,10,20,30,40,50,60,70,80,90,100,150,200,300]:
    hls = tuple(nb_n for i in range(10))
    mlp = nn.MLPClassifier(hidden_layer_sizes=hls)
    st = time.time()
    start_time = time.process_time()
    mlp.fit(datatrain,targettrain)
    elapsed = time.process_time()-start_time
    duration = time.time() - st
    prec = mlp.score(datatest,targettest)
    precisions_neurones.append(prec)
    temps_neurones.append(elapsed)
    tt_neurones.append(duration)
    rap = recall_score(targettest,testpred,average='micro')
    err = zero_one_loss(targettest,testpred)
    rappel_neurones.append(rap)
    erreur_neurones.append(err)
    prec_train = mlp.score(datatrain,targettrain)
    print("precision =", prec, "temps =", elapsed,"sur train =",prec_train, "pour", nb_n,"neurones")

precision = 0.8326190476190476 temps = 277.15625 sur train = 0.8515918367346939 pour 5 neurones
precision = 0.9232380952380952 temps = 250.140625 sur train = 0.9567142857142857 pour 10 neurones
precision = 0.9486666666666667 temps = 276.984375 sur train = 0.987734693877551 pour 20 neurones
precision = 0.9618095238095238 temps = 219.625 sur train = 0.9961836734693877 pour 30 neurones
precision = 0.963952380952381 temps = 289.375 sur train = 0.9947551020408163 pour 40 neurones
precision = 0.969 temps = 349.4375 sur train = 0.9973877551020408 pour 50 neurones
precision = 0.9712857142857143 temps = 321.046875 sur train = 0.9972448979591837 pour 60 neurones
precision = 0.9689523809523809 temps = 298.15625 sur train = 0.994 pour 70 neurones
precision = 0.9755714285714285 temps = 281.21875 sur train = 0.9979795918367347 pour 80 neurones
precision = 0.9758571428571429 temps = 426.359375 sur train = 0.9977551020408163 pour 90 neurones
precision = 0.9750952380952381 temps = 309.5 sur train = 0.9

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('number of neurons')
ax1.set_ylabel('precision', color=color)
ax1.plot([5,10,20,30,40,50,60,70,80,90,100,150,200,300],precisions_neurones,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('rappel', color=color)
ax2.plot([5,10,20,30,40,50,60,70,80,90,100,150,200,300],rappel_neurones,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
plt.plot([5,10,20,30,40,50,60,70,80,90,100,150,200,300],temps_neurones,'+-')
plt.ylabel('training time')
plt.xlabel('number of neurons')
plt.show()

In [ ]:
plt.plot([5,10,20,30,40,50,60,70,80,90,100,150,200,300],tt_neurones,'+-')
plt.ylabel('training time')
plt.xlabel('number of neurons')
plt.show()

In [ ]:
plt.plot([5,10,20,30,40,50,60,70,80,90,100,150,200,300],erreur_neurones,'+-')
plt.ylabel('error')
plt.xlabel('number of neurons')
plt.show()

In [12]:
tpl4 = tuple(i for i in range(10,60,5))
mlp = nn.MLPClassifier(hidden_layer_sizes=tpl4)
start_time = time.process_time()
mlp.fit(datatrain,targettrain)
elapsed = time.process_time() - start_time
prec = mlp.score(datatest,targettest)
print("10 couches: precision =",prec,"temps =",elapsed)
prec_train = mlp.score(datatrain,targettrain)
print(prec_train)

10 couches: precision = 0.930047619047619 temps = 434.75
0.9764081632653061


In [13]:
tpl1 = tuple(60-i for i in range(50))
mlp = nn.MLPClassifier(hidden_layer_sizes=tpl1)
start_time = time.process_time()
mlp.fit(datatrain,targettrain)
elapsed = time.process_time() - start_time
prec = mlp.score(datatest,targettest)
print("50 couches: precision =",prec,"temps =",elapsed)
prec_train = mlp.score(datatrain,targettrain)
print(prec_train)

50 couches: precision = 0.11095238095238096 temps = 136.53125
0.11320408163265307


In [14]:
pas = int(-49/20)
tpl2 = tuple(i for i in range(60,10,pas))
mlp = nn.MLPClassifier(hidden_layer_sizes=tpl2)
start_time = time.process_time()
mlp.fit(datatrain,targettrain)
elapsed = time.process_time() - start_time
prec = mlp.score(datatest,targettest)
print("20 couches: precision =",prec,"temps =",elapsed)
prec_train = mlp.score(datatrain,targettrain)
print(prec_train)

20 couches: precision = 0.97 temps = 348.5625
0.9894693877551021


In [15]:
cm = confusion_matrix(targettest,mlp.predict(datatest))
print(cm)

[[2019    0    6    3    2    2    7    0   13    2]
 [   0 2309    6    3    2    0    2    2    6    0]
 [   1   10 2070   13    6    1    2   12   23    3]
 [   0    4   20 2016    0   17    0    9   33    7]
 [   1    3    3    0 2037    1   10    1    3   29]
 [   2    5    4   45    1 1778   15    1   27    4]
 [   5    6    2    2   17    5 2069    0    8    0]
 [   0   13   14    8   11    0    0 2139    4   14]
 [   1   18   11   12    5   11    6    3 1970    8]
 [   4    5    1    2   19    4    1   18   20 1963]]


In [16]:
tpl3 = tuple(i for i in range(60,13,3))
mlp = nn.MLPClassifier(hidden_layer_sizes=tpl3)
start_time = time.process_time()
mlp.fit(datatrain,targettrain)
elapsed = time.process_time() - start_time
prec = mlp.score(datatest,targettest)
print("20 couches: precision =",prec,"temps =",elapsed)
prec_train = mlp.score(datatrain,targettrain)
print(prec_train)

20 couches: precision = 0.8826190476190476 temps = 43.328125
0.9062448979591837


In [19]:
nb_couches = 10
archi = tuple(50 for i in range(nb_couches))

In [20]:
precisions_algos = []
rappel_algos = []
temps_algos = []
tt_algos = []
erreur_algos = []
for s in ["lbfgs","sgd","adam"]:
    mlp = nn.MLPClassifier(hidden_layer_sizes=archi,solver=s)
    st = time.time()
    start_time = time.process_time()
    mlp.fit(datatrain,targettrain)
    elapsed = time.process_time()-start_time
    duration = time.time()-st
    testpred = mlp.predict(datatest)
    prec = mlp.score(datatest,targettest)
    rap = recall_score(targettest,testpred,average='micro')
    err = zero_one_loss(targettest,testpred)
    precisions_algos.append(prec)
    rappel_algos.append(rap)
    temps_algos.append(elapsed)
    tt_algos.append(duration)
    erreur_algos.append(err)
    print("precision =", prec,"rappel =",rap,"erreur =",err,"temps =",elapsed,"pour",s)

precision = 0.9615238095238096 rappel = 0.9615238095238096 erreur = 0.03847619047619044 temps = 445.21875 pour lbfgs
precision = 0.9580952380952381 rappel = 0.9580952380952381 erreur = 0.04190476190476189 temps = 325.015625 pour sgd
precision = 0.9673333333333334 rappel = 0.9673333333333334 erreur = 0.03266666666666662 temps = 281.375 pour adam


In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('algorithm')
ax1.set_ylabel('precision', color=color)
ax1.plot(["lbfgs","sgd","adam"],precisions_algos,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('rappel', color=color)
ax2.plot(["lbfgs","sgd","adam"],rappel_algos,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
plt.plot(["lbfgs","sgd","adam"],temps_algos,'+-')
plt.ylabel('training time')
plt.xlabel('algorithm')
plt.show()

In [ ]:
plt.plot(["lbfgs","sgd","adam"],tt_algos,'+-')
plt.ylabel('training time')
plt.xlabel('algorithm')
plt.show()

In [ ]:
plt.plot(["lbfgs","sgd","adam"],erreur_algos,'+-')
plt.ylabel('error')
plt.xlabel('algorithm')
plt.show()

In [21]:
precisions_activ = []
rappel_activ = []
temps_activ = []
tt_activ = []
erreur_activ = []
for a in ["identity", "logistic", "tanh", "relu"]:
    mlp = nn.MLPClassifier(hidden_layer_sizes=archi,activation=a)
    st = time.time()
    start_time = time.process_time()
    mlp.fit(datatrain,targettrain)
    elapsed = time.process_time()-start_time
    duration = time.time()-st
    testpred = mlp.predict(datatest)
    prec = mlp.score(datatest,targettest)
    rap = recall_score(targettest,testpred,average='micro')
    err = zero_one_loss(targettest,testpred)
    precisions_activ.append(prec)
    rappel_activ.append(rap)
    temps_activ.append(elapsed)
    tt_activ.append(duration)
    erreur_activ.append(err)
    print("precision =", prec,"rappel =",rap,"erreur =",err,"temps =",elapsed,"pour",a)

precision = 0.910047619047619 rappel = 0.910047619047619 erreur = 0.089952380952381 temps = 431.828125 pour identity
precision = 0.11095238095238096 rappel = 0.11095238095238096 erreur = 0.8890476190476191 temps = 116.296875 pour logistic
precision = 0.9337619047619048 rappel = 0.9337619047619048 erreur = 0.06623809523809521 temps = 288.28125 pour tanh
precision = 0.9673333333333334 rappel = 0.9673333333333334 erreur = 0.03266666666666662 temps = 251.53125 pour relu


In [1]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('activation function')
ax1.set_ylabel('precision', color=color)
ax1.plot(["identity", "logistic", "tanh", "relu"],precisions_activ,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('training time', color=color)
ax2.plot(["identity", "logistic", "tanh", "relu"],temps_activ,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('activation function')
ax1.set_ylabel('precision', color=color)
ax1.plot(["identity", "logistic", "tanh", "relu"],precisions_activ,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('training time', color=color)
ax2.plot(["identity", "logistic", "tanh", "relu"],tt_activ,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('activation function')
ax1.set_ylabel('precision', color=color)
ax1.plot(["identity", "logistic", "tanh", "relu"],precisions_activ,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('rappel', color=color)
ax2.plot(["identity", "logistic", "tanh", "relu"],rappel_activ,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
plt.plot(["identity", "logistic", "tanh", "relu"],temps_activ,'+-')
plt.ylabel('training time')
plt.xlabel('activation function')
plt.show()

In [ ]:
plt.plot(["identity", "logistic", "tanh", "relu"],tt_activ,'+-')
plt.ylabel('training time')
plt.xlabel('activation function')
plt.show()

In [ ]:
plt.plot(["identity", "logistic", "tanh", "relu"],erreur_activ,'+-')
plt.ylabel('error')
plt.xlabel('activation function')
plt.show()

In [ ]:
precisions_regul = []
rappel_regul = []
temps_regul = []
tt_regul = []
erreur_regul = []
for a in [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8]:
    mlp = nn.MLPClassifier(hidden_layer_sizes=archi,alpha=a)
    st = time.time()
    start_time = time.process_time()
    mlp.fit(datatrain,targettrain)
    elapsed = time.process_time()-start_time
    duration = time.time()-st
    testpred = mlp.predict(datatest)
    prec = mlp.score(datatest,targettest)
    rap = recall_score(targettest,testpred,average='micro')
    err = zero_one_loss(targettest,testpred)
    precisions_regul.append(prec)
    rappel_regul.append(rap)
    temps_regul.append(elapsed)
    tt_regul.append(duration)
    erreur_regul.append(err)
    print("precision =", prec,"rappel =",rap,"erreur =",err,"temps =",elapsed,"pour",a)

precision = 0.9705238095238096 rappel = 0.9705238095238096 erreur = 0.029476190476190434 temps = 338.734375 pour 0.1
precision = 0.9665714285714285 rappel = 0.9665714285714285 erreur = 0.033428571428571474 temps = 325.96875 pour 0.01


C:\Users\linam\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


precision = 0.9642380952380952 rappel = 0.9642380952380952 erreur = 0.03576190476190477 temps = 66.0 pour 0.001


In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('regularization')
ax1.set_xscale("log")
ax1.set_ylabel('precision', color=color)
ax1.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],precisions_regul,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('execution time', color=color)
ax2.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],temps_regul,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('regularization')
ax1.set_xscale("log")
ax1.set_ylabel('precision', color=color)
ax1.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],precisions_regul,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('execution time', color=color)
ax2.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],tt_regul,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()s
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

color = 'tab:blue'
ax1.set_xlabel('regularization')
ax1.set_xscale("log")
ax1.set_ylabel('precision', color=color)
ax1.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],precisions_regul,'+-',color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()

color = 'tab:red'
ax2.set_ylabel('rappel', color=color)
ax2.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],rappel_regul,'r+-',color=color)
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
plt.show()

In [ ]:
plt.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],temps_regul,'+-')
plt.ylabel('training time')
plt.xlabel('regularization')
plt.xscale('log')
plt.show()

In [ ]:
plt.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],tt_regul,'+-')
plt.ylabel('training time')
plt.xlabel('regularization')
plt.xscale('log')
plt.show()

In [ ]:
plt.plot([1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8],erreur_regul,'+-')
plt.ylabel('error')
plt.xlabel('regularization')
plt.xscale('log')
plt.show()